### ISSUE TITLE
A[Feature Request]:  Add Option to view PR submitted by a given user

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/BSoC-Website#47] opened 2023-07-04 07:42 UTC
### Is your feature request related to a problem? Please describe.

Currently on the dashboard we just can see ranking score and name, there is no way to see all the PRs submitted by the given user.

### Describe the solution you'd like

One way can be on clicking the person's score / profile, it opens a page listing all the PRs with links and dificulties added by the user. We can either add a completely new page or show the information in a dialog box.

**Comment by RISHIKESHk07** [comment] 2023-07-04 08:11
@Priyansh61 i would like to contribute to this issue

**Comment by Priyansh61** [comment] 2023-07-04 19:57
@RISHIKESHk07 Since it is a bit difficult issue, I would like to know your approach before assigning you this. Feel free to ask any questions you have in mind, I will be glad to help

**Comment by Doraemon012** [comment] 2023-07-08 09:57
@Priyansh61 Sir, I would like to work on this issue. Please assign this to me.
I will make a function to fetch the user's data when any PR is clicked. I will filter user's data. Then, I will display the fetched data on a new page or dialog box.

**Comment by Priyansh61** [comment] 2023-07-09 16:33
@Doraemon012 You are already assigned to a difficult issue, can you please take this one after completing the other one?

**Comment by abansal15** [comment] 2023-07-12 09:28
@Priyansh61 i would like to work on this.

**Comment by abansal15** [comment] 2023-07-12 09:28
@Priyansh61 i want to try and learn something new

**Comment by Predcodes69** [comment] 2023-07-12 09:33
@Priyansh61 Hey, can you please consider assigning this issue to me, I am willing to learn and solve this issue to the best of my capability, asap.

**Comment by Doraemon012** [comment] 2023-07-12 09:36
@Priyansh61 Sir I would like to work on this issue, I have already given my idea. I can complete this by today.

**Comment by Doraemon012** [comment] 2023-07-17 02:06
@Priyansh61 Sir, I would like to work on this issue, please assign this to me. I have completed all my previously assigned issues.

**Comment by Priyansh61** [comment] 2023-07-17 11:50
@Doraemon012 Go ahead! I am assigning you.

**Comment by Priyansh61** [comment] 2023-07-22 09:32
@Doraemon012 What's the status of this issue? we need to verify the PRs of all the contributors once..

**Comment by Doraemon012** [comment] 2023-07-22 19:27
@Priyansh61 Sir, the issue is almost completed. I will open the PR by today evening.

Video:

https://github.com/bsoc-bitbyte/BSoC-Website/assets/116624667/2dfa86c0-8272-4f7c-96e3-096d9710e848

**Comment by Priyansh61** [comment] 2023-07-22 19:36
Great Work! Just make the link hoverable, so that the user is aware that this contains a link to the PRs

**Closed** 2023-08-02 06:20 UTC
Labels: enhancement, difficulty : Hard
